### ISSUE TITLE
Consider documenting configuration keys

### ISSUE THREAD

**Issue by snicoll** [dabla/grizzly-spring-boot-starter#4]
Keys defined in `GrizzlyProperties` aren't documented at the moment and no proper content assistance is available in supported IDEs.

See [the documentation for more details](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor)

**Comment by dabla** [comment]
Done in 1.1-SNAPSHOT.

**Comment by snicoll** [comment]
Thanks but it's not just about adding the processor. Adding field javadoc also makes sure that each key as a dedicated description (basically what you have already in the README). You could try using the starter with an IDE to see in practice how this can help.

**Comment by dabla** [comment]
> Thanks but it's not just about adding the processor. Adding field javadoc also makes sure that each key as a dedicated description (basically what you have already in the README). You could try using the starter with an IDE to see in practice how this can help.

I've added the descriptions from README as commentary in the GrizzlyProperties class so that it's also taken into account by the processor.

**Comment by dabla** [comment]
Hi Stéphane, maybe more a Spring Boot support related question.  But it seems that I've found a possible issue regarding the Spring Boot ServerProperties.  At the moment I'm refactoring the grizzly-spring-boot-starter and preparing a 1.2 release which will use the standard Spring Boot [server properties](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) instead of my own grizzly properties where possible, thus making for the users easier to switch from one container to another.  Still, all Spring Boot server properties work fine, except the server.port property, which always stays at value -1 (even checked will debugging).  All other properties, like server.address, server.servlet.context-path, server.compression.enabled, etc are working fine and are replaced with the values I defined in the application.properties, but no avail with server.port.  For the moment my work around is to still keep the grizzly.http.port property, but it would be nice if I could use the default server.port property.  Maybe I'm doing something wrong or am I missing something.  Thanks in advance, David
